name: Documentation for the Health Record Ingestion service
title: Health Record Ingestion service
description: A deployment-ready service for streaming data into the cloud
theme: jekyll-theme-dinky
github:
  repository_url: https://github.com/Alvearie/HRI
  is_project_page: true
  owner_url: https://github.com/Alvearie/HRI
plugins:
  - jekyll-mentions

jekyll-mentions:
  base_url: https://github.com
